module.exports =  [
    [
        [
            'Создать репозиторий на github под этот курс. Каждое домашнее задание в отдельной ветке.',
            'Просмотреть лекцию. - https://clck.ru/atLCx',
            'Посмотреть дополнительные видео с 11 по 32. - https://clck.ru/atLB7',
            'Ознакомься (не зазубривай, но и не пропускай):',
            'Как сравниваются значения: -http://www.ecma-international.org/ecma-262/#sec-abstract-equality-comparison',
            'Типы данных - https://clck.ru/EgB4V',
            'Математика в Javascript -https://habr.com/ru/post/312880/',
            'Округление чисел в js - https://learn.javascript.ru/number#okruglenie',
            'Console -https://developer.mozilla.org/ru/docs/Web/API/Console',
            'Eslint для проверки js кода - https://eslint.org/',
            'Пройти тест на понимание материала. - https://clck.ru/atLCe',
            'Выполнить домашнее задание - https://clck.ru/atLDd',
            'Все задачи на 8 kyu. - https://www.codewars.com/ ',
        ],
        [
            'Просмотреть лекцию. - https://clck.ru/atS5q',
            'Посмотреть дополнительные видео - https://clck.ru/atS6Z',
            'Ознакомься (не зазубривай, но и не пропускай):',
            'Операторы - https://mzl.la/2OIRxyL',
            'Тернарный оператор - https://mzl.la/2qLfqvZ',
            'Ветвление - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/if...else',
            'Switch - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/switch',
            'Функции - https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Functions',
            'Подробнее про рекурсию - https://habr.com/post/275813/',
            'JSDOC - https://jsdoc.app/',
            'Явное преобразование типов - https://learn.javascript.ru/type-conversions',
            'Побитовые операторы - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/Bitwise_Operators',
            'Принципы чистого кода на Javascript - https://github.com/devSchacht/clean-code-javascript',
            'Ниндзя-код - https://learn.javascript.ru/ninja-code',
            'try catch - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/try...catch',
            'throw - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Statements/throw',
            'Пройти тест на понимание материала. - https://clck.ru/atSGs',
            'Выполнить домашнее задание - https://clck.ru/atSKt'
        ]
    ],
    [
        [
            'Просмотреть лекцию. - https://clck.ru/atUE2',
            'Посмотреть дополнительные видео - https://clck.ru/WeT5W',
            'Пройти тест на понимание материала - https://clck.ru/atUEo',
            'Все задачи на 7 kyu. - https://www.codewars.com/ ',
            'Выполнить домашнее задание - https://clck.ru/atUFA',
            'Циклы и итерации - https://mzl.la/2OSeEqr',
            'Массивы - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array',
            'Методы массивов (слева в навигации) - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Array#',
            'Методы массивов - https://learn.javascript.ru/array-methods',
            'Методы "строк"(объект String) - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/String',
            'Статья "О выборе структур данных для начинающих" (C, C++, Java, C#) - https://habr.com/post/339656/',
            'Статья "Зачем они нужны в JavaScript? Symbol, Iterator, Generator" - https://bit.ly/2Q8Po3U',
            'Правила оформления кода - https://ymatuhin.ru/front-end/javascript_styleguide/,',
            'Визуализация алгоритмов сортировки - https://youtu.be/Gnp8G1_kO3I',
            'Типы set, map, weakset, weakmap - https://webdevblog.ru/kollekcii-javascript-set-and-map/',
            'Object.freeze для "заморозки" объектов - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze'
        ],
        [
            'Просмотреть лекцию. - https://clck.ru/atUaw',
            'Посмотреть дополнительные видео - https://clck.ru/WihSR',
            'Пройти тест на понимание материала - https://clck.ru/atUbA',
            'Выполнить домашнее задание - https://clck.ru/atUbX',
            'Если сложности с this, то посмотри начало этого урока - https://yadi.sk/i/JyT_qD2Pgh6SDQ',
            'Объекты в javascript - https://developer.mozilla.org/ru/docs/Web/JavaScript/Guide/Working_with_Objects',
            'Оператор in - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/in',
            'Классы поддерживаются всеми современными браузерами, кроме IE - https://kangax.github.io/compat-table/es6/#test-class',
            'Статистика использования браузеров - https://radar.yandex.ru/browsers',
            'Можно es6 код привести к es5 с помощью babel: - https://babeljs.io/repl',
            'Сделать объект полноценной константой (заморозить): - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Object/freeze',
        ]
    ],
    [
        [
            'Просмотреть лекцию. - https://clck.ru/atWjY',
            'Посмотреть дополнительные видео -  https://clck.ru/atWkA',
            'ПРАВИЛА ВЫПОЛНЕНИЯ ДЗ - https://clck.ru/atWkJ',
            'Все задачи на 6 kyu. - https://www.codewars.com/ ',
            'Выполнить домашнее задание - https://clck.ru/Wo9cS',
            'Document - https://developer.mozilla.org/ru/docs/Web/API/Document',
            'Класс Node - https://developer.mozilla.org/ru/docs/Web/API/Node',
            'Интерфейс Element - https://developer.mozilla.org/ru/docs/Web/API/Element',
            'Element.insertAjacentHTML - https://developer.mozilla.org/ru/docs/Web/API/Element/insertAdjacentHTML',
            'Element.insertAjacentText - https://developer.mozilla.org/ru/docs/Web/API/Element/insertAdjacentText',
            'Интерфейс Events - https://developer.mozilla.org/en-US/docs/Web/API/Event',
            'Все виды событий - https://developer.mozilla.org/ru/docs/Web/Events',
            'Добавить или удалить атрибут - https://developer.mozilla.org/ru/docs/Web/API/Element/setAttribute',
            'Валидация формы с бутстрапом - http://getbootstrap.com/docs/4.1/components/forms/#validation',
            'Событие change - https://developer.mozilla.org/en-US/docs/Web/Events/change',
            'Событие input - https://developer.mozilla.org/en-US/docs/Web/Events/input',
            'Событие cut - https://developer.mozilla.org/en-US/docs/Web/Events/cut',
            'Событие copy - https://developer.mozilla.org/en-US/docs/Web/Events/copy',
            'Событие paste - https://developer.mozilla.org/en-US/docs/Web/Events/paste',
            'Событие submit - https://developer.mozilla.org/ru/docs/Web/Events/submit'
        ],
        [
            'Просмотреть лекцию. - https://clck.ru/atWkf',
            'Посмотреть дополнительные видео - https://clck.ru/atWkn',
            'Выполнить домашнее задание - https://clck.ru/WsP9X',
            'Number.toString() - https://mzl.la/2rcETPe',
            'HTMLElement.dataset - https://developer.mozilla.org/ru/docs/Web/API/HTMLElement/dataset',
            'Event reference - https://developer.mozilla.org/ru/docs/Web/Events',
            'HTMLMedia?Element - https://developer.mozilla.org/en-US/docs/Web/API/HTMLMediaElement',
            'Проигрыватель Plyr - https://plyr.io/',
            'Слайдер jssor (просто для изучения возможностей) - https://www.jssor.com/',
            'FlexSlider 2 - http://flexslider.woothemes.com/',
            'Animate css - https://daneden.github.io/animate.css/',
            'События анимации - https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/animationend_event',
            'Css свойство animation-fill mode - https://developer.mozilla.org/en-US/docs/Web/CSS/animation-fill-mode',
            'Sweet alert - https://sweetalert2.github.io/#examples',
            'Примеры сторонних библиотек - https://speckyboy.com/top-50-javascript/'
        ],
    ],
    [
        [
            'Просмотреть лекцию. - https://clck.ru/atWmu',
            'Посмотреть дополнительные видео - https://clck.ru/atWn5',
            'Выполнить домашнее задание - https://clck.ru/WwSYm',
            'Awewome js (подборка библиотек на js) - https://github.com/sorrycc/awesome-javascript',
            'Array.prototype.some() - https://mzl.la/2QvlI15',
            'Object.assign() - https://mzl.la/2QcTh91',
            'Object.getOwnPropertyNames() - https://mzl.la/2rhT59m',
            'console.error() - https://mzl.la/2PerYpm',
            'setInterval() - https://mzl.la/2SqNDg1',
            'clearInterval() - https://mzl.la/2G6sPce',
            'Math.floor() - https://mzl.la/2Qx42SO',
            'Math.random() - https://mzl.la/2Sp2lnO',
            'Markdown cheat sheet - https://github.com/sandino/Markdown-Cheatsheet',
            'Отличие декларативного подхода от императивного - https://tproger.ru/translations/imperative-declarative-programming-concepts/',
            'Бесплатный векторный редактор - https://inkscape.org/ru/'
        ],
        [
            'Просмотреть лекцию. - https://clck.ru/atWoE',
            'Посмотреть дополнительные видео - https://clck.ru/atWo8',
            'Выполнить домашнее задание - https://clck.ru/Wzo4o',
            'Тест на понимание - https://clck.ru/atWoK',
            'Анонимные функции - https://mzl.la/2E7Ftp8',
            'Замыкания - https://developer.mozilla.org/ru/docs/Web/JavaScript/Closures',
            'Функции обратного вызова - https://mzl.la/2QdQexf',
            'IIFE - https://metanit.com/web/javascript/3.3.php',
            'This - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/this',
            'Call - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Function/call',
            'Apply - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Function/apply',
            'Bind - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Function/bind',
            'Оператор in - https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Operators/in',
            'ЗАКОНЧИ ВСЕ ТО ЧТО НЕ ДОДЕЛАЛ И ОТДОХНИ 5 ДНЕЙ :) ПОВЕРЬ ЭТО БЫЛ ЛАЙТ'
        ],
    ]
]